### ISSUE TITLE
네이버 로그인 이메일 버그 수정

### ISSUE THREAD

**Issue by kimmand0o0** [E-GaeMuYac/BE#122]
네이버로 소셜 로그인 시 서브 이메일인 gmail이 등록되어 해당 사항 변경이 필요합니다.
소셜 로그인 작업하신 연수님과 협업 하겠습니다 :D

**Comment by kimmand0o0** [comment]
네이버로그인네이버 아이디로 로그인 시 연락처 이메일이 아니라 네이버 이메일 주소를 가져오는 방법 문의
* 문의 내용

오류 현상:현재 네이버 로그인을 사용할 경우 사용자 이메일 정보에 '연락처 이메일' 정보가 제공됩니다.
연락처 이메일을 본인의 네이버 계정이 아닌 다음 또는 네이트 이메일 주소로 입력한 사용자의 경우에는
네이버 로그인을 했어도 다른 회사 이메일 계정을 불러오는 오류가 있습니다.

> 안녕하세요. 네이버 아이디로 로그인(네아로) 입니다.

네아로에서 제공하는 이메일 정보는 '연락처 이메일'에 기재된 이메일 정보가 맞습니다.
네이버ID@naver.com 형식의 이메일은 현재 정책 상 제공하지 않습니다.

업무에 참고 부탁 드립니다.

**Comment by youngjae0411** [comment]
소셜로그인은 유니크를 빼고, 로컬만 중복 안 되게 변경하는걸로 해결하였습니다.
