### ISSUE TITLE
Axios Timeout 에러 해결

### ISSUE THREAD

**Issue by kimmand0o0** [E-GaeMuYac/BE#33]
공공데이터포탈에서 api를 가져오며 스케줄링을 이용한 자동 업데이트를 계획중이다.
Axios를 사용하여 api를 가져올 시 불특정한 타이밍으로 timeout이 발생한다.

이 때, axios 설정으로 timeout을 임의로 설정해주니 아래와 같은 에러가 발생하였다.
`
AxiosError: timeout of 3000000000ms exceede
at RedirectableRequest.handleRequestTimeout (/Users/mandoo/Desktop/sparta/finalPJ/BE/node_modules/axios/dist/node/axios.cjs:2781:16)
    at RedirectableRequest.emit (node:events:527:28)
    at RedirectableRequest.emit (node:domain:475:12)
    at Timeout.<anonymous> (/Users/mandoo/Desktop/sparta/finalPJ/BE/node_modules/follow-redirects/index.js:169:12)
    at listOnTimeout (node:internal/timers:559:17)
    at processTimers (node:internal/timers:502:7) {
  code: 'ECONNABORTED'
`
이 부분을 해결하는 방법을 찾아보려고 한다.

**Comment by youngjae0411** [comment]
불특정한 타이밍으로 timeout이 왜 뜨는건가요?? 공공 api에서 나는건가요??

**Comment by kimmand0o0** [comment]
다른 경우에는 나지 않고 공공 api를 연결 할 때 나며, 데이터의 길이등과 상관없이 for문을 돌리던 중 짧은 타이밍은 5회 정도, 긴 타이밍은 50회 정도에서 났었습니다. 아직 정확한 이유를 알 수 없어 구글링 중입니다.

**Comment by kimmand0o0** [comment]
timeout 설정을 해준 후 아래 error를 만나게 되었다.
너무 많은 요청을 보냈을 경우 나는 에러라고 한다.
이럴 경우 에러가 나는 곳이 공공api 쪽이기 때문에 우리 서버 쪽에서 해결 할 수 있는 방법은 시간을 여러번 나눠서 요청을 보내거나, 요청 자체를 나눠서 보내는 방법이 있을 것 같다.

`AxiosError: read ECONNRESET`

방법을 조금 더 고민 해보기로 한다.

**Comment by kimmand0o0** [comment]
그리고 신기하게 timeout 설정을 30000 이상을 했을 때 진행 자체가 안되는 경우들이 많다. 이런 경우가 왜인 지 확인 해봐야할 것 같다.

**Comment by kimmand0o0** [comment]
아래 코드를 활용하여 Axios 에러를 피해갔습니다.

```
try {
      const { start } = req.query;
      await this.productService.updateProductsMain(start);
      res.redirect('/api/products/apiUpdateType?start=1');
    } catch (error) {
      if (
        error.message.includes(
          'Axios' || 'ECONNRESET' || 'ECONNREFUSED' || 'ETIMEDOUT'
        )
      ) {
        res.redirect(
          `/api/products/apiUpdateMain?start=${error.config.params.pageNo}`
        );
      }
      next(error);
    }
```

매니저님과 멘토님께 조언 받았던 방법들은 잘 먹히지 않았습니다.

이슈 닫겠습니다.
